### ISSUE TITLE
4 nodes Cassandra cluster on 2 servers

### ISSUE THREAD

**Issue by moonsyim** [pokle/cassandra#32]
Hello

seriously I'd like to make 4 nodes Cassandra cluster on 2 servers like

1st Server : Container A, Container B

2st Server : Container C, Container D

Container A, Container C are seed node.

I'd like to make

Container A is linked (bridge) to 1st host eth0

Container B is linked (bridge) to 1st host eth1

Container C is linked (bridge) to 2nd host eth0

Container D is linked (bridge) to 2nd host eth1

but it looks like

Container A, B links to 1st node's eth0 all.

Container C, D links to 2nd node's eth0 all.

–net=host is not good option to me.

Do you have any good suggestion for 4 nodes (4 container) Cassandra cluster on 2 servers ?

**Comment by pokle** [comment]
If you're going to production, I would recommend keeping the ratio of physical server to Cassandra node 1:1.

You can actually set up your cluster topology however you prefer - the shell scripts and dockerfiles are there as a guide - feel free to fork the project and edit to your needs. 

Cheers!
